services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  product:
    build: ./api/product
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        npm run test
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
